### ISSUE TITLE
Bug :: Oversized transaction error

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/optimism-monorepo#289]
**Describe the bug**
We often go over the size limit of transactions when submitting batches. This causes our transactions to fail and generally everyone has a bad day.

**Steps to reproduce**
1. Set the transaction calldata size to a number above 132KB (even slightly below this number)
2. Run the full system
3. Observe errors submitting batches

**Expected behavior**
We should never submit transactions above the maximum size.

**Solution**

### Work-around
Reduce the Max L2 Tx calldata size for a batch:

1. Update the l2_geth_subscriber 's task definition to have a lower CANONICAL_CHAIN_BATCH_MAX_CALLDATA_BYTES value (right now it's 90,000)
2. Update the ECS service to reference the new task definition and restart the ECS task so it picks up the new config (stop it, and it'll restart itself)
3. Run this query to delete created but unsubmitted batches so that they will be rebuilt to fit the lower size limit:

```
BEGIN;

UPDATE l2_tx_output
SET 
	canonical_chain_batch_number = NULL,
	canonical_chain_batch_index = NULL
WHERE canonical_chain_batch_number >= *batch number that is erroring*;

DELETE FROM canonical_chain_batch
WHERE batch_number >= *batch number that is erroring*;

COMMIT;
```

### Solution
Since it _should_ be predictable, accurately calculate the total transaction bytes for the L1 rollup tx (including all the rolled up L2 Txs' bytes) and create batches such that _this_ number of bytes is less than or equal to the `CANONICAL_CHAIN_BATCH_MAX_CALLDATA_BYTES` instead of simply making sure that all of the L2 txs being rolled up are under this number.

**Comment by willmeister** [comment]
Figured out a few different issues with the `CanonicalTransactionChain.appendSequencerBatch(bytes[] memory _txBatch, uint _timestamp, uint _blockNumber, uint _startsAtTxIndex)` Oversized Data issue. Sharing here for visibility + sanity checking.

## Current Approach (that has this issue)

1. Configure Max L2 Rollup Transactions Bytes as env var
a. Notably, this ignores the L1 tx containing these txs, and its encoding to call `appendSequencerBatch(...)`
1. Limit batch size enforcing SUM(L2 rollup tx calldata bytes + standard non-calldata L2 tx overhead bytes) <= Max L2 Rollup Txs Bytes

## Issues with approach causing underestimation
1. L1 tx has 164 bytes of static calldata overhead 
a. Method ID - 4 bytes
a. _txBatch `bytes[]` param start index - 32 bytes
a. _timestamp - 32 bytes
a. _blockNumber - 32 bytes
a. _startsAtIndex - 32 bytes
a. number of `bytes` within `_txBatch` - 32 bytes
1. L1 tx (containing rolled up L2 txs in its calldata) has 64 bytes of overhead for each L2 rollup tx
a. Each encoded `bytes` in the `_txBatch` `bytes[]` requires a `uint` for start index and `uint` for length
1. L2 rollup tx bytes size will always be padded to the nearest multiple of 32 
a. e.g. 140 bytes of data takes up 160 (5*32) bytes from encoding
1. L1 tx has static overhead of ~214 bytes 
a. nonce - 32 bytes
a. gas price - 32 bytes
a. gas limit - 32 bytes
a. value - 32 bytes
a. R (signature) - 32 bytes
a. S (signature) - 32 bytes
a. V (signature) - 2 bytes (at most)
a. to address - 20 bytes

## Curveball
L1 tx will be RLP-encoded, so it will be smaller than 214 static bytes of overhead

I think we should just ignore the RLP savings since we'll only slightly over-count, and that'll give us a bit of room for error. Thoughts?

## Approach
Going to add logic to account for all of the above. Please let me know if you see anything I missed

**Comment by karlfloersch** [comment]
Wow just saw this & this analysis looks awesome! Freaking thorough!  

> Each bytes (L2 tx) in _txBatch will always be padded to the nearest multiple of 32

Oh wow great catch & totally true but very easy to forget about... That's annoying!

> I think we should just ignore the RLP savings since we'll only slightly over-count, and that'll give us a bit of room for error. Thoughts?

Definitely think that this seems like a sensible approach. There's just so much headache that we will have by under-estimating the bytes that it doesn't make sense for us to sweat submitting slightly suboptimal batches. In the long term we can resist this component when we really want to penny pinch, but at the moment I think you've definitely got the right idea.
