### ISSUE TITLE
Revive the monorepo

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism-monorepo#417]
**Is your feature request related to a problem? Please describe.**

Developers have a hard time working with the submodules in optimism-integration. In addition, the fragmentation across repositories has caused us to have cyclical dependencies and creates large operational overheads when making changes which require touching many repositories.

**Describe the solution you'd like**

We should revive the monorepo format and move away from the [submodulesintegrations](https://github.com/ethereum-optimism/optimism-integration) 

There's 4 logical groups for our codebases:
- core: geth (go), core-utils (ts), contracts (sol/ts)
- services (all ts): dtl, ctc/scc batch submitter, relayer, watcher
- tooling such as smock/plugins
- integration tests
- non-core forks: ethereumjs-ovm, solc 

A structure could be that this repository includes the _services_ and _tooling_, and the _core_ and _integration tests_ codebases are grouped in the `go-ethereum` repository. Another structure could be to bundle everything in 1 repository (incl. geth w/ everything else). That way, the `optimism-integration` repository would no longer use submodules, and we'd be able to bundle the integration tests in a single-repo developer workflow (vs having to juggle many PRs right now). We agreed to get rid of ethereumjs-ovm, and I think it's OK to let solc remain in a separate repository.
 
There's a few constraints to take into account:
- Developer Experience should be as close as today, where a user can just `./up.sh` and it "just works"
- The "Docker build ⇒ tag ⇒ release ⇒ deploy" flow should remain intact, so that our devops can still be fully automated

**Comment by gakonst** [comment]
Updated Proposal: 1 repo with *everything*. That's it. If we go monorepo we should go all-in. 

Our structure MUST be integration test oriented. As a result, the integration tests MUST be in the same place as geth/contracts/batch submitters/relayers.

The directory structure would be something like:
```
optimism-monorepo
   l2geth
   contracts
   core-utils
   ctc-batch-submitter
   scc-batch-submitter
   message-relayer
   watcher
   dtl
   smock
   hardhat-plugin
   ...
```

**Comment by karlfloersch** [comment]
This is awesome! I am a big fan of moving back to the monorepo style is ideal, especially if we optimize the CI to preserve the parallelism & speed that we enjoy now. And obviously ideally improve it!

Some notes on the proposal:
- I really like how you called out the strict labeling system & PR review system. IMO the biggest benefit of this approach is that it'll give us a single view for our PRs, issues, and labels. If by having a monorepo we can improve our project management flow & make it easily accessible for contributors that would make me very happy!
- I personally don't enjoy installing global packages and so `yarn add global @eth-optimism/testnet && optimism-testnet` is to me just a nice to have. However, I do know a bunch of folks enjoy the convenience so definitely down.
  - I do think that any CLI that we introduce should be minimally magical / minimally heavy. A good repo structure should make the CLI be mostly just aliases to the particular commands we frequently use as opposed to performing some kind of complex compute. The more compute the more likely we're just reinventing the wheel.
- Reducing the time it takes to: 1) make a small change in a package, and then 2) run the _entire_ system to test if your change effected behavior is _super important_. The way we were going to do this in our current system was to conditionally mount packages, so that you only need to build local images for the services that you've changed. How you achieve a rapid feedback loop between `making a change->verifying the full system still works` is an implementation detail but I do think that is a critical metric to measure as you're building the system.

Overall, @gakonst I'm suuuuper excited to see this thing happen! If we can have:
- a single source of truth for all issues & PRs related to the protocol
- a rapid feedback loop for devs so that features can be tested rapidly & then integration tested immediately afterwards
- fast, parallelized CI, auto building images & publishing based on tags
- good docs for how to use the monorepo / tooling

Then I'ma be simply overjoyed.

Keep us posted on progress!!!! ✅

**Comment by karlfloersch** [comment]
Actually, one follow up question: What do you think about specs? Should they live in the monorepo as well? If so maybe add to directory structure? Oh another one is our homepage -- my guess is we just keep that out of the monorepo for now for simplicity

**Comment by gakonst** [comment]
Specs/homepage should be outside of the monorepo imo, although I could be convinced otherwise. Lower priority in any case.

**Comment by snario** [comment]
I agree that the protocol specifications and landing page make sense to be in external repositories.

The specifications make sense to be external since they're likely to be modified by an external development process than the ones happening in the main development repo. The artifacts are independent MarkDown documents, not software. 

Similarly the landing page is similar to a branding component and isn't dependant on or a dependency of anything related to the development of software that implements the protocol, so it may as well be separate.
